{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.configSecretName" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.tplConfig }}
  config.yaml: {{ tpl (.Values.config | toYaml) $ | b64enc | quote }}
  {{- else }}
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
  {{- end }}
{{- end }}
